# Generated by Django 5.0.3 on 2024-05-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tprobot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ware_house',
            name='ware_house_name',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
