# Generated by Django 5.0 on 2024-05-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tprobot', '0002_remove_ware_house_ware_house_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ware_house',
            name='ware_house_status',
            field=models.BooleanField(default=False),
        ),
    ]
