# Generated by Django 5.0.3 on 2024-04-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tprobot', '0002_rename_d_complete_date_deliver_order_deliver_order_complete_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliver_order',
            name='deliver_order_complete_date',
            field=models.DateTimeField(null=True, verbose_name='입고 완료 일자'),
        ),
        migrations.AlterField(
            model_name='stock_order',
            name='stock_order_complete_date',
            field=models.DateTimeField(null=True, verbose_name='출고 완료 일자'),
        ),
    ]
