# Generated by Django 5.0.3 on 2024-05-02 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tprobot', '0002_ware_house_ware_house_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware_house',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Ware_house', to='tprobot.product'),
        ),
    ]
