# Generated by Django 5.0.3 on 2024-05-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tprobot', '0003_alter_ware_house_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ware_house',
            name='product_id',
        ),
    ]
