# Generated by Django 5.0 on 2024-05-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tprobot', '0003_ware_house_ware_house_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliver_order',
            name='deliver_order_processing',
            field=models.CharField(default='B', max_length=1),
        ),
    ]
