# Generated by Django 5.0.3 on 2024-05-09 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tprobot', '0004_remove_ware_house_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ware_house',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Ware_house', to='tprobot.product'),
        ),
    ]
