# Generated by Django 5.0 on 2024-05-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tprobot', '0005_alter_deliver_order_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='robot_image',
            field=models.ImageField(null=True, upload_to='robots'),
        ),
    ]
